## Introduction to PyTorch 🔥

## Prerequisites
Before starting this tutorial, make sure you have PyTorch installed. You can install it using:
```bash
pip install torch torchvision
```

## Why PyTorch?

PyTorch is one of the leading deep learning frameworks, particularly popular in research and academia. It offers:
- Dynamic computational graphs (unlike static graphs in early TensorFlow)
- Python-first approach with familiar syntax
- Rich ecosystem of tools and libraries
- Strong GPU acceleration support
- Active community and extensive documentation

## About This Tutorial
This tutorial assumes you have basic Python knowledge and understanding of fundamental machine learning concepts. We'll cover:
1. Tensors - The fundamental PyTorch data structure
2. Autograd - Automatic differentiation system
3. Neural Network Modules
4. Training a Simple Neural Network

## 1. PyTorch Tensors
Tensors are similar to arrays but with additional features like GPU support and automatic differentiation tracking.

In [1]:
import torch
import numpy as np

# Create a tensor
x = torch.tensor([1, 2, 3, 4, 5])
print(f"Tensor: {x}")
print(f"Type: {x.dtype}")
print(f"Shape: {x.shape}")


Tensor: tensor([1, 2, 3, 4, 5])
Type: torch.int64
Shape: torch.Size([5])


### Creating Tensors
PyTorch provides multiple ways to create tensors:

In [2]:
# From Python list/NumPy array

array = np.array([1, 2, 3])
tensor_from_array = torch.from_numpy(array)

# Zero tensor
zeros = torch.zeros(3, 2)

# One tensor
ones = torch.ones(2, 2)

# Random tensor
random = torch.rand(2, 3)

print("From array:", tensor_from_array)
print("\nZeros:\n", zeros)
print("\nOnes:\n", ones)
print("\nRandom:\n", random)

From array: tensor([1, 2, 3])

Zeros:
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Ones:
 tensor([[1., 1.],
        [1., 1.]])

Random:
 tensor([[0.1351, 0.2982, 0.9185],
        [0.7382, 0.9896, 0.3468]])


### Tensor Operations
PyTorch supports various operations similar to NumPy:

In [3]:
# Basic arithmetic

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Matrix Multiplication:", torch.matmul(a, b))

# Reshaping
c = torch.tensor([[1, 2], [3, 4]])
print("\nOriginal:\n", c)
print("Reshaped:", c.reshape(1, 4))


Addition: tensor([5, 7, 9])
Multiplication: tensor([ 4, 10, 18])
Matrix Multiplication: tensor(32)

Original:
 tensor([[1, 2],
        [3, 4]])
Reshaped: tensor([[1, 2, 3, 4]])


### GPU Support
One of PyTorch's key features is seamless GPU support:

In [4]:
# Check if GPU is available

if torch.backends.mps.is_available():
    device = torch.device("mps")  # Use Metal Performance Shaders on Apple Silicon
elif torch.cuda.is_available():
    device = torch.device("cuda")  # Use CUDA for NVIDIA GPUs
else:
    device = torch.device("cpu")  # Fallback to CPU
    
print(f"Using device: {device}")

# Move tensor to GPU if available
x = torch.tensor([1, 2, 3])
x = x.to(device)


Using device: mps


## 2. Autograd: Automatic Differentiation
PyTorch's autograd system enables automatic computation of gradients:

In [5]:
# Create tensors with gradient tracking

x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# Perform operations
z = x**2 + y**3

# Compute gradients
z.backward()

print(f"dz/dx: {x.grad}")  # Should be 4.0 (derivative of x^2 is 2x)
print(f"dz/dy: {y.grad}")  # Should be 27.0 (derivative of y^3 is 3y^2)

dz/dx: 4.0
dz/dy: 27.0


## 3. Neural Network Modules
PyTorch provides a high-level API for building neural networks through `torch.nn`:

In [6]:
import torch.nn as nn

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.layer1 = nn.Linear(10, 5)
        self.layer2 = nn.Linear(5, 1)
        self.relu = nn.ReLU()
        
    def forward(self, x):
        x = self.relu(self.layer1(x))
        x = self.layer2(x)
        return x

# Create model instance
model = SimpleNN()
print(model)

SimpleNN(
  (layer1): Linear(in_features=10, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=1, bias=True)
  (relu): ReLU()
)


## 4. Training a Simple Neural Network
Let's put everything together to train a simple neural network:

In [7]:
import torch.optim as optim

# Generate synthetic data
X = torch.randn(100, 10)  # 100 samples, 10 features
y = torch.sum(X, dim=1, keepdim=True) * 0.1  # Simple target function

# Model, loss function, and optimizer
model = SimpleNN()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    # Forward pass
    outputs = model(X)
    loss = criterion(outputs, y)
    
    # Backward pass and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 20 == 0:
        print(f'Epoch [{epoch+1}/100], Loss: {loss.item():.4f}')

Epoch [20/100], Loss: 0.1257
Epoch [40/100], Loss: 0.0927
Epoch [60/100], Loss: 0.0800
Epoch [80/100], Loss: 0.0738
Epoch [100/100], Loss: 0.0696


## Common PyTorch Patterns and Best Practices


### 1. Data Loading
PyTorch provides efficient data loading utilities:

In [8]:
from torch.utils.data import Dataset, DataLoader

# Custom dataset
class CustomDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
        
    def __len__(self):
        return len(self.X)
    
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

# Create data loader
dataset = CustomDataset(X, y)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

### 2. Model Saving and Loading

In [9]:
# Save model
torch.save(model.state_dict(), 'model.pth')

# Load model
loaded_model = SimpleNN()
loaded_model.load_state_dict(torch.load('model.pth'))


/var/folders/31/vhwm53rj4tnfvv9lgq9m3x5w0000gn/T/ipykernel_77994/4089310465.py:6: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_model.load_state_dict(torch.load('mode

<All keys matched successfully>

### 3. Training and Evaluation Modes

In [10]:
# Training mode
model.train()
# ... training code ...

# Evaluation mode
model.eval()
with torch.no_grad():  # Disable gradient computation
    test_output = model(X)

## Common Layers and Activation Functions
PyTorch provides many built-in layers:

In [11]:
# Common layers
conv = nn.Conv2d(3, 64, kernel_size=3)  # Convolutional layer
pool = nn.MaxPool2d(2)  # Max pooling
dropout = nn.Dropout(0.5)  # Dropout
batch_norm = nn.BatchNorm2d(64)  # Batch normalization

# Activation functions
relu = nn.ReLU()
sigmoid = nn.Sigmoid()


## Next Steps
To continue learning PyTorch:
1. Explore the [PyTorch documentation](https://pytorch.org/docs/stable/index.html)
2. Try implementing different neural network architectures
3. Practice with real-world datasets
4. Experiment with more advanced features like custom loss functions and optimizers